### ISSUE TITLE
Packaged for Archlinux

### ISSUE THREAD

**Issue by sionleroux** [fridex/hexsticker#5]
Hi I made an AUR package for version 1.2.0 so that it's easy to install on Arch Linux: https://aur.archlinux.org/packages/hexsticker

For example with `yay` you can install it like this:

```bash
yay -S hexsticker
```

Maybe it would be useful to mention this at the bottom of the README, but if not then it's okay to close this issue, I just wanted to give a heads up :wink:

**Comment by fridex** [comment]
Hi @sinisterstuf, this is great! Would you mind submitting a PR with instructions and links? It's definitely worth stating. Thank you!

**Comment by sionleroux** [comment]
Ok the PR is here: #7
